<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423195741 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE asset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, symbol VARCHAR(10) NOT NULL, asset_type VARCHAR(10) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE asset_quote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, quote NUMERIC(12, 4) DEFAULT NULL, asset_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE2AE5B35DA1941 ON asset_quote (asset_id)');
        $this->addSql('CREATE TABLE daily_performance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fee NUMERIC(14, 4) DEFAULT NULL, tax NUMERIC(14, 4) DEFAULT NULL, realized_earnings NUMERIC(14, 4) DEFAULT NULL, realized_earnings_current_year NUMERIC(14, 4) DEFAULT NULL, cash NUMERIC(14, 4) DEFAULT NULL, leftover NUMERIC(14, 4) DEFAULT NULL, bought_value NUMERIC(14, 4) DEFAULT NULL, sold_value NUMERIC(14, 4) DEFAULT NULL, currently_invested NUMERIC(14, 4) DEFAULT NULL, current_value NUMERIC(14, 4) DEFAULT NULL, potential_earnings NUMERIC(14, 4) DEFAULT NULL, overal_earnings NUMERIC(14, 4) DEFAULT NULL, date DATE NOT NULL, user_asset_trading_place_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5691459E595E045F ON daily_performance (user_asset_trading_place_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_uastp_date ON daily_performance (user_asset_trading_place_id, date)');
        $this->addSql('CREATE TABLE trading_place (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE transaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, transaction_type VARCHAR(10) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, price NUMERIC(12, 4) NOT NULL, quantity NUMERIC(12, 4) NOT NULL, fee NUMERIC(12, 4) DEFAULT NULL, asset_id INT NOT NULL, user_id INT NOT NULL, trading_place_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_723705D15DA1941 ON transaction (asset_id)');
        $this->addSql('CREATE INDEX IDX_723705D1A76ED395 ON transaction (user_id)');
        $this->addSql('CREATE INDEX IDX_723705D1D7A30618 ON transaction (trading_place_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE user_asset_trading_place (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tradingplace_user_id INT NOT NULL, asset_id INT NOT NULL, trading_place_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_29FFFDF5B445FB91 ON user_asset_trading_place (tradingplace_user_id)');
        $this->addSql('CREATE INDEX IDX_29FFFDF55DA1941 ON user_asset_trading_place (asset_id)');
        $this->addSql('CREATE INDEX IDX_29FFFDF5D7A30618 ON user_asset_trading_place (trading_place_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_asset_tradingplace ON user_asset_trading_place (tradingplace_user_id, asset_id, trading_place_id)');
        $this->addSql('CREATE TABLE watchlist_asset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, symbol VARCHAR(10) NOT NULL, name VARCHAR(255) NOT NULL, quote NUMERIC(20, 10) NOT NULL, change DOUBLE PRECISION DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SYMBOL ON watchlist_asset (symbol)');
        $this->addSql('CREATE TABLE watchlist_asset_user (watchlist_asset_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (watchlist_asset_id, user_id))');
        $this->addSql('CREATE INDEX IDX_51D945F4284DE094 ON watchlist_asset_user (watchlist_asset_id)');
        $this->addSql('CREATE INDEX IDX_51D945F4A76ED395 ON watchlist_asset_user (user_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE asset_quote ADD CONSTRAINT FK_FE2AE5B35DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE daily_performance ADD CONSTRAINT FK_5691459E595E045F FOREIGN KEY (user_asset_trading_place_id) REFERENCES user_asset_trading_place (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D15DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1D7A30618 FOREIGN KEY (trading_place_id) REFERENCES trading_place (id)');
        $this->addSql('ALTER TABLE user_asset_trading_place ADD CONSTRAINT FK_29FFFDF5B445FB91 FOREIGN KEY (tradingplace_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_asset_trading_place ADD CONSTRAINT FK_29FFFDF55DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_asset_trading_place ADD CONSTRAINT FK_29FFFDF5D7A30618 FOREIGN KEY (trading_place_id) REFERENCES trading_place (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE watchlist_asset_user ADD CONSTRAINT FK_51D945F4284DE094 FOREIGN KEY (watchlist_asset_id) REFERENCES watchlist_asset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE watchlist_asset_user ADD CONSTRAINT FK_51D945F4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE asset_quote DROP CONSTRAINT FK_FE2AE5B35DA1941');
        $this->addSql('ALTER TABLE daily_performance DROP CONSTRAINT FK_5691459E595E045F');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D15DA1941');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1A76ED395');
        $this->addSql('ALTER TABLE transaction DROP CONSTRAINT FK_723705D1D7A30618');
        $this->addSql('ALTER TABLE user_asset_trading_place DROP CONSTRAINT FK_29FFFDF5B445FB91');
        $this->addSql('ALTER TABLE user_asset_trading_place DROP CONSTRAINT FK_29FFFDF55DA1941');
        $this->addSql('ALTER TABLE user_asset_trading_place DROP CONSTRAINT FK_29FFFDF5D7A30618');
        $this->addSql('ALTER TABLE watchlist_asset_user DROP CONSTRAINT FK_51D945F4284DE094');
        $this->addSql('ALTER TABLE watchlist_asset_user DROP CONSTRAINT FK_51D945F4A76ED395');
        $this->addSql('DROP TABLE asset');
        $this->addSql('DROP TABLE asset_quote');
        $this->addSql('DROP TABLE daily_performance');
        $this->addSql('DROP TABLE trading_place');
        $this->addSql('DROP TABLE transaction');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_asset_trading_place');
        $this->addSql('DROP TABLE watchlist_asset');
        $this->addSql('DROP TABLE watchlist_asset_user');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
