<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260316081934 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE watchlist_asset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, symbol VARCHAR(10) NOT NULL, name VARCHAR(255) NOT NULL, quote NUMERIC(20, 10) NOT NULL, change DOUBLE PRECISION DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, app_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC7CC1B04A3353D8 ON watchlist_asset (app_user_id)');
        $this->addSql('ALTER TABLE watchlist_asset ADD CONSTRAINT FK_AC7CC1B04A3353D8 FOREIGN KEY (app_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE watchlist_asset DROP CONSTRAINT FK_AC7CC1B04A3353D8');
        $this->addSql('DROP TABLE watchlist_asset');
    }
}
