<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260429194944 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cash_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, amount NUMERIC(14, 4) NOT NULL, description VARCHAR(255) DEFAULT NULL, user_trading_place_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_890918BAAB644C5 ON cash_event (user_trading_place_id)');
        $this->addSql('ALTER TABLE cash_event ADD CONSTRAINT FK_890918BAAB644C5 FOREIGN KEY (user_trading_place_id) REFERENCES user_trading_place (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cash_event DROP CONSTRAINT FK_890918BAAB644C5');
        $this->addSql('DROP TABLE cash_event');
    }
}
