<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260426084404 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE trading_place_performance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, cash NUMERIC(14, 4) DEFAULT NULL, tax NUMERIC(14, 4) DEFAULT NULL, paid_tax_current_year NUMERIC(14, 4) DEFAULT NULL, taxable_earnings NUMERIC(14, 4) DEFAULT NULL, realized_earnings_current_year NUMERIC(14, 4) DEFAULT NULL, realized_earnings NUMERIC(14, 4) DEFAULT NULL, overall_earnings NUMERIC(14, 4) DEFAULT NULL, user_trading_place_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_54C333FEAAB644C5 ON trading_place_performance (user_trading_place_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_utp_date ON trading_place_performance (user_trading_place_id, date)');
        $this->addSql('CREATE TABLE user_trading_place (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, starting_cash NUMERIC(14, 4) NOT NULL, tax_rate NUMERIC(5, 4) NOT NULL, tax_free_pot NUMERIC(14, 4) NOT NULL, tradingplace_user_id INT NOT NULL, trading_place_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2EC7E6B6B445FB91 ON user_trading_place (tradingplace_user_id)');
        $this->addSql('CREATE INDEX IDX_2EC7E6B6D7A30618 ON user_trading_place (trading_place_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_trading_place ON user_trading_place (tradingplace_user_id, trading_place_id)');
        $this->addSql('ALTER TABLE trading_place_performance ADD CONSTRAINT FK_54C333FEAAB644C5 FOREIGN KEY (user_trading_place_id) REFERENCES user_trading_place (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_trading_place ADD CONSTRAINT FK_2EC7E6B6B445FB91 FOREIGN KEY (tradingplace_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_trading_place ADD CONSTRAINT FK_2EC7E6B6D7A30618 FOREIGN KEY (trading_place_id) REFERENCES trading_place (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE daily_performance ADD overall_earnings NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE daily_performance DROP cash');
        $this->addSql('ALTER TABLE daily_performance DROP overal_earnings');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE trading_place_performance DROP CONSTRAINT FK_54C333FEAAB644C5');
        $this->addSql('ALTER TABLE user_trading_place DROP CONSTRAINT FK_2EC7E6B6B445FB91');
        $this->addSql('ALTER TABLE user_trading_place DROP CONSTRAINT FK_2EC7E6B6D7A30618');
        $this->addSql('DROP TABLE trading_place_performance');
        $this->addSql('DROP TABLE user_trading_place');
        $this->addSql('ALTER TABLE daily_performance ADD overal_earnings NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE daily_performance RENAME COLUMN overall_earnings TO cash');
    }
}
